In [ ]:
import numpy as np

In [9]:
x = [[1,2], [3,4]]
s=0
for i in x:
    s = s + sum(i)
print(s)



10


In [11]:
nx = np.array(x)
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

10
1
4
2.5
1.118033988749895
1.25


In [12]:
type(nx)

numpy.ndarray

In [14]:
print(nx.shape)   # shape of ,matrix
print(nx.size)    # total elements
print(nx.dtype)   # type of elements

(2, 2)
4
int64


In [17]:
z = [[1,2,3], [3,4,2], [5,6,7]]
nc = np.array(z)
print(nc.shape)

(3, 3)


functions to create matrix
- `arange`: create a range of numbers
- `linspace`: create a matrix of specified number of elements
- `ones`: create a matrix of ones
- `zeros`: create a matrix of zeros
- `random.randint`: create a matrix of random integers
- `random.rand`: create a matrix of random floats
- `diag`: create a matrix with diagonal elements

In [18]:
a  = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [21]:
np.arange(1,5,.05)

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05,
       2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 ,
       2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15,
       3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 ,
       3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25,
       4.3 , 4.35, 4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 ,
       4.85, 4.9 , 4.95])

In [24]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [27]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
np.random.randint(1, 100, 10)

array([86, 62, 60,  8, 44, 61, 59, 61,  4, 31], dtype=int32)

In [32]:
np.random.randint(-5, 6, (5,5))

array([[-1,  0, -3, -5, -3],
       [ 3, -4, -1, -3, -3],
       [ 4, -1,  0,  1,  1],
       [-1, -1, -5,  1,  1],
       [-2, -2,  5,  2,  2]], dtype=int32)

In [33]:
np.random.rand(5)  # num  of elements

array([0.24345821, 0.23005684, 0.33527362, 0.85684528, 0.6283692 ])

In [34]:
np.random.rand(10,5)  # 10*10 matrix

array([[0.81969758, 0.73932115, 0.34397134, 0.32225956, 0.46136862],
       [0.32749272, 0.08327326, 0.56009507, 0.25767182, 0.2897287 ],
       [0.97086876, 0.53046769, 0.24770055, 0.26908551, 0.48400223],
       [0.65744344, 0.75289268, 0.29977269, 0.99977604, 0.35342191],
       [0.61175334, 0.06111421, 0.63689161, 0.34316445, 0.47088473],
       [0.6055257 , 0.68842814, 0.5626601 , 0.27932134, 0.91499931],
       [0.41200953, 0.88538482, 0.24451518, 0.52147511, 0.7418215 ],
       [0.69767172, 0.7176825 , 0.69036018, 0.1643262 , 0.53555866],
       [0.57598564, 0.91514214, 0.04166469, 0.43443612, 0.44793301],
       [0.34255712, 0.9349121 , 0.50416741, 0.02284651, 0.04090887]])

In [35]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.394, 0.344, 0.682, 0.009, 0.869],
       [0.088, 0.683, 0.905, 0.346, 0.406],
       [0.879, 0.121, 0.576, 0.574, 0.598],
       [0.705, 0.657, 0.027, 0.061, 0.526],
       [0.184, 0.742, 0.653, 0.115, 0.886],
       [0.061, 0.743, 0.563, 0.837, 0.411],
       [0.158, 0.871, 0.257, 0.278, 0.119],
       [0.478, 0.193, 0.302, 0.907, 0.934],
       [0.789, 0.964, 0.04 , 0.406, 0.845],
       [0.209, 0.183, 0.85 , 0.802, 0.403]])

In [36]:
x = [1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [42]:
# reshape
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
x=np.linspace(1,5,25).reshape(5,5)

In [49]:
x.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [52]:
y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [53]:
y.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [54]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
                      

[[2 8 1]
 [9 6 5]
 [3 4 4]]
[[8 2 7]
 [1 8 9]
 [3 3 4]]


In [55]:
a+b

array([[10, 10,  8],
       [10, 14, 14],
       [ 6,  7,  8]], dtype=int32)

In [56]:
a.dot(b)  # dot product (matrix multiplication)

array([[ 27,  71,  90],
       [ 93,  81, 137],
       [ 40,  50,  73]], dtype=int32)

In [57]:
a*b

array([[16, 16,  7],
       [ 9, 48, 45],
       [ 9, 12, 16]], dtype=int32)

In [58]:
a/b

array([[0.25 , 4.   , 0.143],
       [9.   , 0.75 , 0.556],
       [1.   , 1.333, 1.   ]])

In [59]:
a-b

array([[-6,  6, -6],
       [ 8, -2, -4],
       [ 0,  1,  0]], dtype=int32)

In [61]:
a+10  # add 10 to all elememts

array([[12, 18, 11],
       [19, 16, 15],
       [13, 14, 14]], dtype=int32)

# STATS

In [62]:
print(a.mean())

4.666666666666667


In [64]:
a.mean(axis=0)  # column wise mean
a.mean(axis=1)  # row wise mean

array([4.667, 6.   , 3.333])

In [66]:
print(a.sum())
print(a.sum(axis=0)) # column wise sum
print(a.sum(axis=1)) # row wise sum

42
[14 18 10]
[11 20 11]


In [67]:
np.sin(a)

array([[ 0.909,  0.989,  0.841],
       [ 0.412, -0.279, -0.959],
       [ 0.141, -0.757, -0.757]])

In [69]:
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[7.389e+00 2.981e+03 2.718e+00]
 [8.103e+03 4.034e+02 1.484e+02]
 [2.009e+01 5.460e+01 5.460e+01]]
[[1.414 2.828 1.   ]
 [3.    2.449 2.236]
 [1.732 2.    2.   ]]
9
1


In [70]:
x = np.random.randint(1,100,(2,5))
print(x)

[[ 5 24 64 23 44]
 [98 52 15 89 29]]


In [71]:
print(x.max())  # max element
print(x.argmax()) # index of max element
print(x.min()) # min value element
print(x.argmin()) # min value element

98
5
5
0
