In [2]:
import numpy as np

In [ ]:
x = [[1,2], [3,4]]
s=0
for i in x:
    s = s + sum(i)
print(s)



In [ ]:
nx = np.array(x)
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

In [ ]:
type(nx)

In [ ]:
print(nx.shape)   # shape of ,matrix
print(nx.size)    # total elements
print(nx.dtype)   # type of elements

In [ ]:
z = [[1,2,3], [3,4,2], [5,6,7]]
nc = np.array(z)
print(nc.shape)

functions to create matrix
- `arange`: create a range of numbers
- `linspace`: create a matrix of specified number of elements
- `ones`: create a matrix of ones
- `zeros`: create a matrix of zeros
- `random.randint`: create a matrix of random integers
- `random.rand`: create a matrix of random floats
- `diag`: create a matrix with diagonal elements

In [ ]:
a  = np.arange(1,50)
print(a)

In [ ]:
np.arange(1,5,.05)

In [ ]:
np.linspace(1,100,10)

In [ ]:
np.ones((3,3), dtype=int)

In [ ]:
np.zeros((2,4), dtype=int)

In [ ]:
np.random.randint(1, 100, 10)

In [ ]:
np.random.randint(-5, 6, (5,5))

In [ ]:
np.random.rand(5)  # num  of elements

In [ ]:
np.random.rand(10,5)  # 10*10 matrix

In [ ]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

In [ ]:
x = [1,2,3,4,5]
np.diag(x)

In [ ]:
# reshape
np.arange(10).reshape(5,2)

In [ ]:
x=np.linspace(1,5,25).reshape(5,5)

In [ ]:
x.flatten()

In [ ]:
y = np.arange(1,26).reshape(5,5)
print(y)

In [ ]:
y.T

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
                      

In [ ]:
a+b

In [ ]:
a.dot(b)  # dot product (matrix multiplication)

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
a-b

In [ ]:
a+10  # add 10 to all elememts

# STATS

In [ ]:
print(a.mean())

In [ ]:
a.mean(axis=0)  # column wise mean
a.mean(axis=1)  # row wise mean

In [ ]:
print(a.sum())
print(a.sum(axis=0)) # column wise sum
print(a.sum(axis=1)) # row wise sum

In [ ]:
np.sin(a)

In [ ]:
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

In [ ]:
x = np.random.randint(1,100,(2,5))
print(x)

In [ ]:
print(x.max())  # max element
print(x.argmax()) # index of max element
print(x.min()) # min value element
print(x.argmin()) # min value element

# slicing
- 1D
- 2D

In [5]:
x = np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)
print(x[0]) # row index 0
print(x[-1]) # last row
print(x[2]) # row index 2
print(x[:3]) # row index 0 to 2
print(x[-2:]) # last 2 rows

print(x[:,0]) # column index 0
print(x[:,-1]) # last column
print(x[1:4,:3]) # column 2 and 3
print(x[2:-1,2:]) 

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[[ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1 21 42 62 83]
[ 17  38  58  79 100]
[[21 25 29]
 [42 46 50]
 [62 67 71]]
[[50 54 58]
 [71 75 79]]


FILTERING

In [6]:
x > 50 # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
x[x>50] # filter values greater than 50 - broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [9]:
x[(x>40) & (x<80)]  # filter values greater than 40 or less than 80, '&' is bitwise and 

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [8]:
x[x % 2 == 0] # filter even numbers

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

#3rd party libraries

- `plotly` - Interactive plots using HTML
- `matplotlib` - Plotting Library for almost all types of plots (Image)
- `seaborn` - Plotting library for statistical plots (Extension of matplotlib)
- `statsmodels` - for support in seaborn
- `scipy` - for support in Seaborn
- `nbformat` - for support in plotly